# Información del proyecto
sonar.projectKey=ITM_ENTREGA4
sonar.projectName=Products API
sonar.projectVersion=1.0

# Configuración de código fuente
sonar.sources=.
sonar.exclusions=vendor/**,test/**,public/**,.scannerwork/**,coverage/**

# Configuración de pruebas
sonar.tests=test
sonar.test.inclusions=test/**/*Test.php
sonar.test.exclusions=vendor/**

# Reportes de pruebas (SIN cobertura por falta de Xdebug)
sonar.php.tests.reportPath=coverage/junit.xml

# Configuración de idioma
sonar.sourceEncoding=UTF-8
sonar.php.file.suffixes=php